### ISSUE TITLE
extra_parameters are not working as expected

### ISSUE THREAD

**Issue by ghost** [Turgon37/ansible-apache2#19]
Hi!

I've tried the example in your README.md:
```yaml
apache2__host_virtual_hosts:
  proxy-https:
    hosts:
      - ip: 10.0.0.1
      - ip: 192.168.56.12
    server_name: www.example.net
    server_alias: www2.example.net
    extra_parameters:
      - 'ProxyRequests Off'
      - 'ProxyPreserveHost On'
      - 'ProxyPass / http://localhost:3001/'
      - 'ProxyPassReverse / https://localhost:3001/'
    https:
      certificate_file: /etc/ssl/apache2/www.example.net.pem
      certificate_key_file: /etc/ssl/apache2/www.example.net.key
```

It's not working as expected; the extra_parameters are not in the proxy-https site config. I got it working with the directives switch:
```yaml
apache2__virtual_hosts_host:
  proxy-https:
    hosts:
      - ip: 10.0.0.1
      - ip: 192.168.56.12
    server_name: www.example.net
    server_alias: www2.example.net
    directives:
      - extra_parameters:
        - 'ProxyRequests Off'
        - 'ProxyPreserveHost On'
        - 'ProxyPass / http://localhost:3001/'
        - 'ProxyPassReverse / https://localhost:3001/'
    https:
      certificate_file: /etc/ssl/apache2/www.example.net.pem
      certificate_key_file: /etc/ssl/apache2/www.example.net.key
```

I'm pretty sure this was meant to work the other way around.

Regards,
Bostjan
